# 01_deseq2_analysis.R
#
# Purpose: Trisomy-aware differential expression analysis using DESeq2
#          Compares T21 vs Control samples with ploidy normalization for chr21
#
# Inputs:
#   - data/processed/count_matrix.csv
#   - data/processed/sample_metadata.csv
#   - data/processed/gene_annotations.csv
#
# Outputs:
#   - results/tables/deseq2_results_all_genes.csv
#   - results/tables/deseq2_chr21_genes.csv
#   - results/figures/pca_plot.pdf
#   - results/figures/dispersion_plot.pdf
#   - results/figures/ma_plot.pdf
#
# Date: 2025-11-11

# Load required libraries
library(tidyverse)
library(DESeq2)

# Set seed for reproducibility
set.seed(42)

cat("=== T21-eQTL Analysis: Trisomy-Aware DESeq2 ===\n\n")

# Create output directories
dir.create("results/tables", recursive = TRUE, showWarnings = FALSE)
dir.create("results/figures", recursive = TRUE, showWarnings = FALSE)

# =============================================================================
# STEP 1: Load preprocessed data
# =============================================================================

cat("Step 1: Loading preprocessed data...\n")

# Check that required files exist
required_files <- c("data/processed/count_matrix.csv",
                    "data/processed/sample_metadata.csv",
                    "data/processed/gene_annotations.csv")

for (file in required_files) {
  if (!file.exists(file)) {
    stop(sprintf("Required file not found: %s\nRun 00_preprocess_data.R first.",
                 file))
  }
}

# Load data
count_data <- read_csv("data/processed/count_matrix.csv",
                       show_col_types = FALSE)
metadata <- read_csv("data/processed/sample_metadata.csv",
                     show_col_types = FALSE)
gene_annotations <- read_csv("data/processed/gene_annotations.csv",
                             show_col_types = FALSE)

# Extract count matrix (remove annotation columns)
count_matrix <- count_data %>%
  select(-Gene_name, -Chr) %>%
  column_to_rownames("EnsemblID") %>%
  as.matrix()

# Round counts to integers (DESeq2 requirement)
count_matrix <- round(count_matrix)

cat(sprintf("  Count matrix: %d genes x %d samples\n",
            nrow(count_matrix), ncol(count_matrix)))
cat(sprintf("  Metadata: %d samples (%d T21, %d Control)\n",
            nrow(metadata),
            sum(metadata$Karyotype == "T21"),
            sum(metadata$Karyotype == "Control")))
cat(sprintf("  Gene annotations: %d genes (%d on chr21)\n",
            nrow(gene_annotations),
            sum(gene_annotations$Chr == "chr21")))

# =============================================================================
# STEP 2: Prepare DESeq2 inputs
# =============================================================================

cat("\nStep 2: Preparing DESeq2 inputs...\n")

# Ensure metadata is in same order as count matrix columns
metadata <- metadata %>%
  filter(LabID %in% colnames(count_matrix)) %>%
  arrange(match(LabID, colnames(count_matrix)))

# Verify order
stopifnot(all(metadata$LabID == colnames(count_matrix)))
cat("  Sample order verified\n")

# Create colData for DESeq2
col_data <- DataFrame(
  sample_id = metadata$LabID,
  karyotype = factor(metadata$Karyotype, levels = c("Control", "T21")),
  sex = factor(metadata$Sex),
  age = metadata$Age_at_visit,
  bmi = metadata$BMI
)
rownames(col_data) <- metadata$LabID

cat(sprintf("  Design: ~karyotype (Control vs T21)\n"))

# =============================================================================
# STEP 3: Create ploidy normalization matrix
# =============================================================================

cat("\nStep 3: Creating ploidy normalization matrix...\n")

# From Hunter et al. (2023):
# "The normalization matrix was generated by assigning each gene in the
# analysis its ploidy number divided by 2. For all genes not on chromosome 21,
# this number was thus 1. For genes on chromosome 21 samples in trisomy,
# this number was 1.5."

# Get chr21 genes
chr21_genes <- gene_annotations %>%
  filter(Chr == "chr21") %>%
  pull(EnsemblID)

# Get T21 samples
t21_samples <- metadata %>%
  filter(Karyotype == "T21") %>%
  pull(LabID)

cat(sprintf("  Chr21 genes: %d\n", length(chr21_genes)))
cat(sprintf("  T21 samples: %d\n", length(t21_samples)))

# Create ploidy normalization matrix (ploidy / 2)
# - Non-chr21 genes in all samples: 2/2 = 1.0
# - Chr21 genes in Control samples: 2/2 = 1.0
# - Chr21 genes in T21 samples: 3/2 = 1.5
norm_matrix <- matrix(1.0,
                      nrow = nrow(count_matrix),
                      ncol = ncol(count_matrix))
rownames(norm_matrix) <- rownames(count_matrix)
colnames(norm_matrix) <- colnames(count_matrix)

chr21_idx <- which(rownames(norm_matrix) %in% chr21_genes)
t21_idx <- which(colnames(norm_matrix) %in% t21_samples)

if (length(chr21_idx) > 0 && length(t21_idx) > 0) {
  norm_matrix[chr21_idx, t21_idx] <- 1.5
}

cat(sprintf("  Ploidy matrix created: %d x %d\n",
            nrow(norm_matrix), ncol(norm_matrix)))
cat(sprintf("  Normalization factors: 1.5 (T21 chr21), 1.0 (all others)\n"))

# Verify normalization matrix
stopifnot(nrow(norm_matrix) == nrow(count_matrix))
stopifnot(ncol(norm_matrix) == ncol(count_matrix))
stopifnot(all(norm_matrix == 1.0 | norm_matrix == 1.5))
cat("  Ploidy matrix validation: PASSED\n")

# =============================================================================
# STEP 4: Run DESeq2 WITHOUT ploidy normalization (to get raw fold changes)
# =============================================================================

cat("\nStep 4: Running DESeq2 WITHOUT ploidy normalization...\n")
cat("  (This gives raw fold changes to identify chr21 genes >= 1.5 FC)\n")

# Create DESeqDataSet without ploidy normalization
dds_raw <- DESeqDataSetFromMatrix(
  countData = count_matrix,
  colData = col_data,
  design = ~ karyotype
)

# CRITICAL: Exclude chr21 genes from size factor calculation
# Chr21 genes are overexpressed in T21, so including them biases normalization
cat("  Calculating size factors (excluding chr21 genes)...\n")
non_chr21_genes <- !rownames(dds_raw) %in% chr21_genes
dds_raw <- estimateSizeFactors(dds_raw, controlGenes = non_chr21_genes)

cat("  Running DESeq2 (no ploidy normalization)...\n")
dds_raw <- DESeq(dds_raw, betaPrior = FALSE)

# Extract results
results_raw <- results(dds_raw, name = "karyotype_T21_vs_Control")

# Convert to table
results_raw_table <- as.data.frame(results_raw) %>%
  rownames_to_column("EnsemblID") %>%
  left_join(gene_annotations, by = "EnsemblID") %>%
  select(EnsemblID, Gene_name, Chr, Gene_type,
         baseMean, log2FoldChange, lfcSE, stat, pvalue, padj) %>%
  arrange(padj, desc(abs(log2FoldChange)))

cat("  Raw analysis complete\n")

# =============================================================================
# STEP 5: Run DESeq2 WITH ploidy normalization
# =============================================================================

cat("\nStep 5: Running DESeq2 WITH ploidy normalization...\n")
cat("  (This tests if chr21 genes < 1.5 FC are truly DE)\n")

# Create DESeqDataSet with ploidy normalization
dds_norm <- DESeqDataSetFromMatrix(
  countData = count_matrix,
  colData = col_data,
  design = ~ karyotype
)

# Apply ploidy normalization matrix
# From Hunter et al.: normMatrix = ploidy / 2
# Chr21 in T21 = 1.5, all others = 1.0
normalizationFactors(dds_norm) <- norm_matrix
cat("  Ploidy normalization applied (T21 chr21 = 1.5, others = 1.0)\n")

cat("  Running DESeq2 (with ploidy normalization)...\n")
dds_norm <- DESeq(dds_norm, betaPrior = FALSE)

# Extract results
results_norm <- results(dds_norm, name = "karyotype_T21_vs_Control")

# Convert to table
results_norm_table <- as.data.frame(results_norm) %>%
  rownames_to_column("EnsemblID") %>%
  left_join(gene_annotations, by = "EnsemblID") %>%
  select(EnsemblID, Gene_name, Chr, Gene_type,
         baseMean, log2FoldChange, lfcSE, stat, pvalue, padj) %>%
  arrange(padj, desc(abs(log2FoldChange)))

cat("  Ploidy-normalized analysis complete\n")

# =============================================================================
# STEP 6: Compare results and create combined table
# =============================================================================

cat("\nStep 6: Creating combined results table...\n")

# Combine both analyses
# Raw FC is used to determine if gene >= 1.5 FC (log2FC >= 0.585)
# Ploidy-normalized padj is used to determine if gene is truly DE
results_combined <- results_raw_table %>%
  select(EnsemblID, Gene_name, Chr, Gene_type, baseMean,
         raw_log2FC = log2FoldChange,
         raw_pvalue = pvalue,
         raw_padj = padj) %>%
  left_join(
    results_norm_table %>%
      select(EnsemblID,
             norm_log2FC = log2FoldChange,
             norm_pvalue = pvalue,
             norm_padj = padj),
    by = "EnsemblID"
  )

cat(sprintf("  Combined table created: %d genes\n", nrow(results_combined)))

# Chr21 statistics
chr21_combined <- results_combined %>%
  filter(Chr == "chr21")

chr21_raw_median <- median(chr21_combined$raw_log2FC, na.rm = TRUE)
chr21_norm_median <- median(chr21_combined$norm_log2FC, na.rm = TRUE)

cat(sprintf("\n  Chr21 genes (%d total):\n", nrow(chr21_combined)))
cat(sprintf("    Raw median log2FC: %.3f (expected: ~0.585, i.e., 1.5x)\n",
            chr21_raw_median))
cat(sprintf("    Normalized median log2FC: %.3f (expected: ~0)\n",
            chr21_norm_median))

# Count chr21 genes by category
chr21_expected_dosage <- sum(chr21_combined$raw_log2FC >= log2(1.5), na.rm = TRUE)
chr21_below_expected <- sum(chr21_combined$raw_log2FC < log2(1.5), na.rm = TRUE)

cat(sprintf("    Genes >= 1.5 FC: %d\n", chr21_expected_dosage))
cat(sprintf("    Genes < 1.5 FC: %d\n", chr21_below_expected))

# =============================================================================
# STEP 7: Save results
# =============================================================================

cat("\nStep 7: Saving results...\n")

# Main results files with clear names
write_csv(results_combined, "results/tables/deseq2_all_genes_both_analyses.csv")
cat("  Saved: results/tables/deseq2_all_genes_both_analyses.csv\n")
cat("         (All genes with raw_log2FC and norm_log2FC columns)\n")

write_csv(chr21_combined, "results/tables/deseq2_chr21_genes_both_analyses.csv")
cat("  Saved: results/tables/deseq2_chr21_genes_both_analyses.csv\n")
cat("         (Chr21 genes with raw_log2FC and norm_log2FC columns)\n")

# Individual analysis results (for reference)
write_csv(results_raw_table, "results/tables/deseq2_all_genes_no_ploidy_norm.csv")
cat("  Saved: results/tables/deseq2_all_genes_no_ploidy_norm.csv\n")
cat("         (All genes, no ploidy normalization - use for FC >= 1.5 filter)\n")

write_csv(results_norm_table, "results/tables/deseq2_all_genes_ploidy_normalized.csv")
cat("  Saved: results/tables/deseq2_all_genes_ploidy_normalized.csv\n")
cat("         (All genes, ploidy normalized - use for DE testing)\n")

# =============================================================================
# STEP 8: Generate QC plots
# =============================================================================

cat("\nStep 8: Generating QC plots...\n")

# PCA plot (using raw data without ploidy normalization)
vsd <- vst(dds_raw, blind = FALSE)
pca_data <- plotPCA(vsd, intgroup = "karyotype", returnData = TRUE)
percent_var <- round(100 * attr(pca_data, "percentVar"))

pdf("results/figures/pca_plot.pdf", width = 8, height = 6)
pca_plot <- ggplot(pca_data, aes(x = PC1, y = PC2, color = karyotype)) +
  geom_point(size = 3, alpha = 0.8) +
  scale_color_manual(values = c("Control" = "#00BFC4", "T21" = "#F8766D"),
                     name = "Karyotype") +
  xlab(paste0("PC1: ", percent_var[1], "% variance")) +
  ylab(paste0("PC2: ", percent_var[2], "% variance")) +
  ggtitle("PCA Plot: T21 vs Control") +
  theme_bw() +
  theme(legend.position = "right",
        legend.title = element_text(face = "bold"))
print(pca_plot)
dev.off()
cat("  Saved: results/figures/pca_plot.pdf\n")

# Dispersion plot (raw analysis)
pdf("results/figures/dispersion_plot.pdf", width = 8, height = 6)
plotDispEsts(dds_raw, main = "Dispersion Estimates (Raw)")
dev.off()
cat("  Saved: results/figures/dispersion_plot.pdf\n")

# MA plots comparing raw vs normalized
pdf("results/figures/ma_plot.pdf", width = 10, height = 10)
par(mfrow = c(2, 2))

# Raw - All genes
plotMA(results_raw, main = "MA Plot: Raw (All Genes)", ylim = c(-3, 3))
abline(h = c(0, log2(1.5)), col = c("red", "blue"), lty = 2)
legend("topright", legend = c("FC=1", "FC=1.5"),
       col = c("red", "blue"), lty = 2, bty = "n", cex = 0.8)

# Raw - Chr21 highlighted
plotMA(results_raw, main = "MA Plot: Raw (Chr21 Highlighted)", ylim = c(-3, 3))
abline(h = c(0, log2(1.5)), col = c("red", "blue"), lty = 2)
chr21_in_results <- rownames(results_raw) %in% chr21_genes
points(results_raw$baseMean[chr21_in_results],
       results_raw$log2FoldChange[chr21_in_results],
       col = "darkgreen", pch = 20, cex = 0.8)
legend("topright", legend = c("Chr21", "FC=1", "FC=1.5"),
       col = c("darkgreen", "red", "blue"),
       pch = c(20, NA, NA), lty = c(NA, 2, 2), bty = "n", cex = 0.8)

# Normalized - All genes
plotMA(results_norm, main = "MA Plot: Ploidy-Normalized (All Genes)", ylim = c(-3, 3))
abline(h = 0, col = "red", lty = 2)

# Normalized - Chr21 highlighted
plotMA(results_norm, main = "MA Plot: Ploidy-Normalized (Chr21)", ylim = c(-3, 3))
abline(h = 0, col = "red", lty = 2)
chr21_in_results_norm <- rownames(results_norm) %in% chr21_genes
points(results_norm$baseMean[chr21_in_results_norm],
       results_norm$log2FoldChange[chr21_in_results_norm],
       col = "darkgreen", pch = 20, cex = 0.8)
legend("topright", legend = c("Chr21", "FC=1"),
       col = c("darkgreen", "red"),
       pch = c(20, NA), lty = c(NA, 2), bty = "n", cex = 0.8)

dev.off()
cat("  Saved: results/figures/ma_plot.pdf\n")

# =============================================================================
# STEP 9: Summary statistics
# =============================================================================

cat("\n=== DESeq2 Analysis Summary ===\n")

# Sample information
cat(sprintf("\nSample groups:\n"))
cat(sprintf("  Control: %d samples\n",
            sum(col_data$karyotype == "Control")))
cat(sprintf("  T21: %d samples\n",
            sum(col_data$karyotype == "T21")))

# Overall statistics (raw analysis)
cat(sprintf("\nAll genes (raw analysis):\n"))
cat(sprintf("  Total genes tested: %d\n", nrow(results_raw_table)))
sig_raw <- sum(results_raw_table$padj < 0.05, na.rm = TRUE)
cat(sprintf("  Significant genes (padj < 0.05): %d (%.1f%%)\n",
            sig_raw, 100 * sig_raw / nrow(results_raw_table)))

# Chromosome 21 statistics
cat(sprintf("\nChromosome 21 genes:\n"))
cat(sprintf("  Total genes: %d\n", nrow(chr21_combined)))
cat(sprintf("  Genes >= 1.5 FC (raw): %d (%.1f%%)\n",
            chr21_expected_dosage,
            100 * chr21_expected_dosage / nrow(chr21_combined)))
cat(sprintf("  Genes < 1.5 FC (raw): %d (%.1f%%)\n",
            chr21_below_expected,
            100 * chr21_below_expected / nrow(chr21_combined)))

# Chr21 fold change distributions
cat(sprintf("\n  Raw log2FC:\n"))
cat(sprintf("    Median: %.3f (expected: ~%.3f for 1.5x)\n",
            chr21_raw_median, log2(1.5)))
cat(sprintf("    Range: [%.3f, %.3f]\n",
            min(chr21_combined$raw_log2FC, na.rm = TRUE),
            max(chr21_combined$raw_log2FC, na.rm = TRUE)))

cat(sprintf("\n  Ploidy-normalized log2FC:\n"))
cat(sprintf("    Median: %.3f (expected: ~0)\n", chr21_norm_median))
cat(sprintf("    Range: [%.3f, %.3f]\n",
            min(chr21_combined$norm_log2FC, na.rm = TRUE),
            max(chr21_combined$norm_log2FC, na.rm = TRUE)))

# Chr21 genes significantly DE after ploidy normalization
chr21_norm_sig <- sum(chr21_combined$norm_padj < 0.05, na.rm = TRUE)
cat(sprintf("\n  Significantly DE (ploidy-normalized, padj < 0.05): %d\n",
            chr21_norm_sig))

if (chr21_norm_sig > 0) {
  cat("\n  Top chr21 DE genes after ploidy normalization:\n")
  top_chr21_norm <- chr21_combined %>%
    filter(norm_padj < 0.05) %>%
    arrange(norm_padj) %>%
    select(Gene_name, raw_log2FC, norm_log2FC, norm_padj, baseMean) %>%
    head(10)
  print(as.data.frame(top_chr21_norm), row.names = FALSE)
} else {
  cat("\n  No chr21 genes significantly DE after ploidy normalization\n")
  cat("  This is expected - most chr21 genes should be at expected dosage!\n")
}

# Save session info
writeLines(capture.output(sessionInfo()),
           "results/tables/deseq2_session_info.txt")
cat("\nSaved session info to results/tables/deseq2_session_info.txt\n")

cat("\n=== DESeq2 Analysis Complete ===\n")
cat("Next step: Run 02_categorize_genes.R\n\n")
