# 05_sankeymatic_export.R
#
# Purpose: Export the chr21 lane flow as SankeyMATIC input. The lane-flow
#          figure is rendered at https://sankeymatic.com/build/ by pasting
#          results/tables/chr21_lane_sankeymatic_input.txt; the tracked
#          render is docs/figures/Sankey.png (SankeyMATIC default colours).
#          A ggalluvial rendering of the same flow was retired on 2026-09-04.
#
#          Flow structure (scripts/lib/sankey_flow.R):
#            Level 1: Chr21 protein-coding
#            Level 2: Expected dosage / Not assessable / Outside dosage
#                     expectation. Hunter et al.'s rule on the PLOIDY-
#                     CORRECTED scale (padj < 0.01 AND |corrected log2FC| >=
#                     log2(1.5)), read off sig_lane - never off
#                     passes_magnitude_filter, which is FALSE for repeat-
#                     flagged and low-expression genes because they are not
#                     assessable, not because they follow dosage expectation.
#            Level 3: High repeats / Low expression; DE high / DE low.
#            Level 4: eQTL terminal for the DE arms (cis eQTL / no cis eQTL /
#                     no GTEx QTL), shared by both arms. Other lanes
#                     terminate at level 2 or 3.
#
# Inputs:
#   - results/tables/chr21_lane_assignments.csv   (script 04)
#
# Outputs:
#   - results/tables/chr21_lane_flow.csv
#   - results/tables/chr21_lane_sankeymatic_input.txt
#   - results/tables/chr21_lane_sankeymatic_session_info.txt

suppressPackageStartupMessages(library(data.table))
source("scripts/lib/sankey_flow.R")

cat("=== T21-eQTL: SankeyMATIC export ===\n\n")

# =============================================================================
# STEP 1: Load lane assignments
# =============================================================================

cat("Step 1: Loading lane assignments...\n")
lanes <- fread("results/tables/chr21_lane_assignments.csv")
cat(sprintf("  chr21 genes: %d\n", nrow(lanes)))

# =============================================================================
# STEP 2: Flow table
# =============================================================================

cat("\nStep 2: Building flow table...\n")
flow <- lane_flow_table(lanes)
fwrite(flow, "results/tables/chr21_lane_flow.csv")
stopifnot(file.exists("results/tables/chr21_lane_flow.csv"))
cat(sprintf("  Wrote results/tables/chr21_lane_flow.csv (%d paths)\n", nrow(flow)))
print(flow)

# =============================================================================
# STEP 3: SankeyMATIC input
# =============================================================================

cat("\nStep 3: Writing SankeyMATIC input...\n")
sm_lines <- sankeymatic_lines(flow)

header <- c(
  "// Chr21 lane assignment - paste into https://sankeymatic.com/build/",
  "// Generated by scripts/05_sankeymatic_export.R",
  paste0("// Deviating = padj < 0.01 AND abs(ploidy-corrected log2FC) >= ",
         "log2(1.5) (Hunter et al.'s rule);"),
  "// cis eQTL = gene-level permutation test q_gene_bh < FDR_GENE.",
  paste0("// Total genes: ", sum(flow$n_genes)),
  ""
)

sm_path <- "results/tables/chr21_lane_sankeymatic_input.txt"
writeLines(c(header, sm_lines), sm_path)
stopifnot(file.exists(sm_path))
cat(sprintf("  Wrote %s (%d flow lines)\n", sm_path, length(sm_lines)))
writeLines(paste0("    ", sm_lines))

# =============================================================================
# STEP 4: Verification
# =============================================================================

cat("\n=== Verification ===\n")
stopifnot(sum(flow$n_genes) == nrow(lanes))
n_de       <- sum(lanes$sig_lane %in% c("DE_high", "DE_low"))
n_terminal <- sum(flow[level3 %in% DE_LEVEL3, n_genes])
cat(sprintf(paste0("Genes in flow: %d (expect %d); DE genes reaching an eQTL ",
                   "terminal: %d (expect %d)\n"),
            sum(flow$n_genes), nrow(lanes), n_terminal, n_de))
stopifnot(n_terminal == n_de)

cat("\neQTL terminal counts:\n")
print(flow[level3 %in% DE_LEVEL3, .(n_genes = sum(n_genes)), by = level4])

writeLines(capture.output(sessionInfo()),
           "results/tables/chr21_lane_sankeymatic_session_info.txt")
stopifnot(file.exists("results/tables/chr21_lane_sankeymatic_session_info.txt"))

cat("\n=== SankeyMATIC export complete ===\n")

# =============================================================================
# CHANGELOG
# =============================================================================
# 2026-09-04  RETIRED the ggalluvial rendering (chr21_lane_alluvial.{pdf,png});
#             the lane flow is drawn in SankeyMATIC from the exported input.
#             Script renamed from 05_alluvial_lane_assignment.R; the flow CSV
#             renamed from chr21_lane_alluvial_flow.csv to chr21_lane_flow.csv;
#             session info moved to results/tables/.
#             FIXED the export, which had lost both DE arms and all three eQTL
#             terminals: level 3 had been relabelled to tier notation while
#             the level-4 rule and the stratum orders still matched the old
#             "[corrected log2FC ...]" strings, so every DE gene fell through
#             to NA. The mapping now lives in scripts/lib/sankey_flow.R, uses
#             the short node names of docs/figures/Sankey.png, errors instead
#             of dropping unmatched genes, and is pinned by
#             tests/testthat/test-sankey-flow.R.
#
# 2026-08-31  FIXED the level-2 split, which was taken from
#             passes_magnitude_filter and drew all 41 repeat-flagged and
#             low-expression genes inside "Expected dosage". Level 2 now reads
#             sig_lane and gives them their own "Not assessable" arm.
